// eslint-disable-next-line import/prefer-default-export
export const department = {
  1: "Aerospace Engineering",
  2: "Biological Sciences and Bioengineering",
  3: "Chemical Engineering",
  4: "Civil Engineering",
  5: "Computer Science and Engineering",
  6: "Electrical Engineering",
  7: "Materials Science and Engineering",
  8: "Mechanical Engineering",
  9: "Chemistry",
  10: "Economics",
  11: "Earth Sciences",
  12: "Mathematics and Scientific Computing",
  13: "Physics",
  14: "Cognitive Sciences",
  15: "Design Department",
  16: "Environmental Engineering and Management",
  17: "Industrial Management and Engineering",
  18: "Materials Science Program",
  19: "Nuclear Engineering and Technology",
  20: "Photonics Science and Engineering",
  21: "Statistics",
  22: "Humanities and Social Sciences",
  23: "Mathematics",
  24: "Sustainable Energy Engineering",
};
