programExpanded = [
    "BT",
    "BS",
    "DoubleMajor",
    "DualA",
    "DualB",
    "DualC",
    "MT",
    "MSR",
    "MSc",
    "MDes",
    "MBA",
    "PhD",
]

Branches = [
    "AE",
    "BSBE",
    "CE",
    "CHE",
    "CSE",
    "EE",
    "MSE",
    "ME",
    "CHM",
    "ECO",
    "ES",
    "MTH",
    "SDS",
    "PHY",
    "CGS",
    "DES",
    "MS",
    "MSP",
    "NET",
    "PSE",
    "Stats",
    "HSS",
    "Mathematics",
    "SEE",
    "SSA",
]
AE = "AE"
BSBE = "BSBE"
CE = "CE"
CHE = "CHE"
CSE = "CSE"
EE = "EE"
MSE = "MSE"
ME = "ME"
CHM = "CHM"
ECO = "ECO"
ES = "ES"
MTH = "MTH"
SDS = "SDS"
PHY = "PHY"
CGS = "CGS"
DES = "DES"
MS = "MS"
MSP = "MSP"
NET = "NET"
PSE = "PSE"
Stats = "Stats"
HSS = "HSS"
Mathematics = "Mathematics"
SEE = "SEE"
SSA = "SSA"
BT = "BT"
BS = "BS"
MT = "MT"
DoubleMajor = "DoubleMajor"
DualA = "DualA"
DualB = "DualB"
DualC = "DualC"
MDes = "MDes"
MBA = "MBA"
PhD = "PhD"
MSc = "MSc"
MSR = "MSR"

idx = 95
reversemap = dict()

master = {
    AE: {
        BT: 1,
        BS: -1,
        MT: 14,
        DoubleMajor: 28,
        DualA: 38,
        DualB: 49,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 63,
        MSc: -1,
        MSR: 85,
    },
    BSBE: {
        BT: 2,
        BS: -1,
        MT: 15,
        DoubleMajor: 29,
        DualA: 39,
        DualB: 50,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 64,
        MSc: -1,
        MSR: -1,
    },
    CE: {
        BT: 3,
        BS: -1,
        MT: 16,
        DoubleMajor: 30,
        DualA: 40,
        DualB: 51,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 65,
        MSc: -1,
        MSR: 86,
    },
    CHE: {
        BT: 4,
        BS: -1,
        MT: 17,
        DoubleMajor: 31,
        DualA: 41,
        DualB: 52,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 66,
        MSc: -1,
        MSR: 87,
    },
    CSE: {
        BT: 5,
        BS: -1,
        MT: 18,
        DoubleMajor: 32,
        DualA: 42,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 67,
        MSc: -1,
        MSR: 88,
    },
    EE: {
        BT: 6,
        BS: -1,
        MT: 19,
        DoubleMajor: 33,
        DualA: 43,
        DualB: 54,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 68,
        MSc: -1,
        MSR: 89,
    },
    MSE: {
        BT: 7,
        BS: -1,
        MT: 20,
        DoubleMajor: 34,
        DualA: 44,
        DualB: 55,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 69,
        MSc: -1,
        MSR: -1,
    },
    ME: {
        BT: 8,
        BS: -1,
        MT: 21,
        DoubleMajor: 35,
        DualA: 0,
        DualB: 0,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 70,
        MSc: -1,
        MSR: 90,
    },
    CHM: {
        BT: -1,
        BS: 9,
        MT: -1,
        DoubleMajor: 0,
        DualA: -1,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 0,
        MSc: 0,
        MSR: -1,
    },
    ECO: {
        BT: -1,
        BS: 10,
        MT: -1,
        DoubleMajor: 36,
        DualA: 46,
        DualB: 56,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 0,
        MSc: 0,
        MSR: -1,
    },
    ES: {
        BT: -1,
        BS: 11,
        MT: 22,
        DoubleMajor: -1,
        DualA: -1,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 71,
        MSc: 0,
        MSR: -1,
    },
    MTH: {
        BT: -1,
        BS: 12,
        MT: -1,
        DoubleMajor: 37,
        DualA: 47,
        DualB: 0,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: -1,
        MSc: -1,
        MSR: -1,
    },
    SDS: {
        BT: -1,
        BS: 0,
        MT: -1,
        DoubleMajor: 0,
        DualA: 0,
        DualB: 0,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: -1,
        MSc: -1,
        MSR: -1,
    },
    PHY: {
        BT: -1,
        BS: 13,
        MT: -1,
        DoubleMajor: 0,
        DualA: 48,
        DualB: 57,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 73,
        MSc: 0,
        MSR: -1,
    },
    CGS: {
        BT: -1,
        BS: -1,
        MT: -1,
        DoubleMajor: -1,
        DualA: -1,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 74,
        MSc: -1,
        MSR: 91,
    },
    DES: {
        BT: -1,
        BS: -1,
        MT: -1,
        DoubleMajor: -1,
        DualA: -1,
        DualB: 58,
        DualC: -1,
        MDes: 61,
        MBA: -1,
        PhD: 75,
        MSc: -1,
        MSR: -1,
    },
    MS: {
        BT: -1,
        BS: -1,
        MT: 23,
        DoubleMajor: -1,
        DualA: -1,
        DualB: 0,
        DualC: 60,
        MDes: -1,
        MBA: 62,
        PhD: 76,
        MSc: -1,
        MSR: -1,
    },
    MSP: {
        BT: -1,
        BS: -1,
        MT: 24,
        DoubleMajor: -1,
        DualA: -1,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 0,
        MSc: -1,
        MSR: -1,
    },
    NET: {
        BT: -1,
        BS: -1,
        MT: 25,
        DoubleMajor: -1,
        DualA: -1,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 77,
        MSc: -1,
        MSR: -1,
    },
    PSE: {
        BT: -1,
        BS: -1,
        MT: 26,
        DoubleMajor: -1,
        DualA: -1,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 78,
        MSc: -1,
        MSR: 93,
    },
    Stats: {
        BT: -1,
        BS: -1,
        MT: -1,
        DoubleMajor: -1,
        DualA: -1,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 79,
        MSc: 83,
        MSR: -1,
    },
    HSS: {
        BT: -1,
        BS: -1,
        MT: -1,
        DoubleMajor: -1,
        DualA: -1,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 80,
        MSc: -1,
        MSR: -1,
    },
    Mathematics: {
        BT: -1,
        BS: -1,
        MT: -1,
        DoubleMajor: -1,
        DualA: -1,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 81,
        MSc: 84,
        MSR: -1,
    },
    SEE: {
        BT: -1,
        BS: -1,
        MT: 27,
        DoubleMajor: -1,
        DualA: -1,
        DualB: 0,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 82,
        MSc: -1,
        MSR: 94,
    },
    SSA: {
        BT: -1,
        BS: -1,
        MT: 0,
        DoubleMajor: -1,
        DualA: -1,
        DualB: -1,
        DualC: -1,
        MDes: -1,
        MBA: -1,
        PhD: 0,
        MSc: -1,
        MSR: -1,
    }
}

for (index, program) in enumerate(programExpanded):
    for (ii, branchi) in enumerate(Branches):
        if master[Branches[ii]][program] == 0:
            master[Branches[ii]][program] = idx
            idx += 1
        if master[Branches[ii]][program] != -1:
            reversemap[master[Branches[ii]][program]
                       ] = program + "-" + Branches[ii]

print(master)
print(reversemap)
