export const programExpanded = [
  "BT",
  "BS",
  "DoubleMajor",
  "DualA",
  "DualB",
  "DualC",
  "MT",
  "MSR",
  "MSc",
  "MDes",
  "MBA",
  "PhD",
];

export const programCondensed = [
  "BT/BS/Double Major",
  "Dual",
  "MT/MSc/MSR",
  "MDes",
  "MBA",
  "PhD",
];

export const Branches = [
  "AE",
  "BSBE",
  "CE",
  "CHE",
  "CSE",
  "EE",
  "MSE",
  "ME",
  "CHM",
  "ECO",
  "ES",
  "MTH",
  "SDS",
  "PHY",
  "CGS",
  "DES",
  "IME",
  "MSP",
  "NET",
  "PSE",
  "Stats",
  "HSS",
  "Mathematics",
  "SEE",
  "SSA",
];

export type programType = {
  BT: number;
  BS: number;
  MT: number;
  DoubleMajor: number;
  DualA: number;
  DualB: number;
  DualC: number;
  MDes: number;
  MBA: number;
  PhD: number;
  MSc: number;
  MSR: number;
};

export const func = {
  AE: {
    BT: 1,
    BS: -1,
    MT: 14,
    DoubleMajor: 28,
    DualA: 38,
    DualB: 49,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 63,
    MSc: -1,
    MSR: 85,
  },
  BSBE: {
    BT: 2,
    BS: -1,
    MT: 15,
    DoubleMajor: 29,
    DualA: 39,
    DualB: 50,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 64,
    MSc: -1,
    MSR: -1,
  },
  CE: {
    BT: 3,
    BS: -1,
    MT: 16,
    DoubleMajor: 30,
    DualA: 40,
    DualB: 51,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 65,
    MSc: -1,
    MSR: 86,
  },
  CHE: {
    BT: 4,
    BS: -1,
    MT: 17,
    DoubleMajor: 31,
    DualA: 41,
    DualB: 52,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 66,
    MSc: -1,
    MSR: 87,
  },
  CSE: {
    BT: 5,
    BS: -1,
    MT: 18,
    DoubleMajor: 32,
    DualA: 42,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 67,
    MSc: -1,
    MSR: 88,
  },
  EE: {
    BT: 6,
    BS: -1,
    MT: 19,
    DoubleMajor: 33,
    DualA: 43,
    DualB: 54,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 68,
    MSc: -1,
    MSR: 89,
  },
  MSE: {
    BT: 7,
    BS: -1,
    MT: 20,
    DoubleMajor: 34,
    DualA: 44,
    DualB: 55,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 69,
    MSc: -1,
    MSR: -1,
  },
  ME: {
    BT: 8,
    BS: -1,
    MT: 21,
    DoubleMajor: 35,
    DualA: 99,
    DualB: 101,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 70,
    MSc: -1,
    MSR: 90,
  },
  CHM: {
    BT: -1,
    BS: 9,
    MT: -1,
    DoubleMajor: 96,
    DualA: 45,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 111,
    MSc: 107,
    MSR: -1,
  },
  ECO: {
    BT: -1,
    BS: 10,
    MT: -1,
    DoubleMajor: 36,
    DualA: 46,
    DualB: 56,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 112,
    MSc: 108,
    MSR: -1,
  },
  ES: {
    BT: -1,
    BS: 11,
    MT: 22,
    DoubleMajor: -1,
    DualA: -1,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 71,
    MSc: 109,
    MSR: -1,
  },
  MTH: {
    BT: -1,
    BS: 12,
    MT: -1,
    DoubleMajor: 37,
    DualA: 47,
    DualB: 102,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: -1,
    MSc: -1,
    MSR: -1,
  },
  SDS: {
    BT: -1,
    BS: 95,
    MT: -1,
    DoubleMajor: 97,
    DualA: 100,
    DualB: 103,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: -1,
    MSc: -1,
    MSR: -1,
  },
  PHY: {
    BT: -1,
    BS: 13,
    MT: -1,
    DoubleMajor: 98,
    DualA: 48,
    DualB: 57,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 73,
    MSc: 110,
    MSR: -1,
  },
  CGS: {
    BT: -1,
    BS: -1,
    MT: -1,
    DoubleMajor: -1,
    DualA: -1,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 74,
    MSc: -1,
    MSR: 91,
  },
  DES: {
    BT: -1,
    BS: -1,
    MT: -1,
    DoubleMajor: -1,
    DualA: -1,
    DualB: 58,
    DualC: -1,
    MDes: 61,
    MBA: -1,
    PhD: 75,
    MSc: -1,
    MSR: -1,
  },
  IME: {
    BT: -1,
    BS: -1,
    MT: 23,
    DoubleMajor: -1,
    DualA: -1,
    DualB: 104,
    DualC: 60,
    MDes: -1,
    MBA: 62,
    PhD: 76,
    MSc: -1,
    MSR: -1,
  },
  MSP: {
    BT: -1,
    BS: -1,
    MT: 24,
    DoubleMajor: -1,
    DualA: -1,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 113,
    MSc: -1,
    MSR: -1,
  },
  NET: {
    BT: -1,
    BS: -1,
    MT: 25,
    DoubleMajor: -1,
    DualA: -1,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 77,
    MSc: -1,
    MSR: -1,
  },
  PSE: {
    BT: -1,
    BS: -1,
    MT: 26,
    DoubleMajor: -1,
    DualA: -1,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 78,
    MSc: -1,
    MSR: 93,
  },
  Stats: {
    BT: -1,
    BS: -1,
    MT: -1,
    DoubleMajor: -1,
    DualA: -1,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 79,
    MSc: 83,
    MSR: -1,
  },
  HSS: {
    BT: -1,
    BS: -1,
    MT: -1,
    DoubleMajor: -1,
    DualA: -1,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 80,
    MSc: -1,
    MSR: -1,
  },
  Mathematics: {
    BT: -1,
    BS: -1,
    MT: -1,
    DoubleMajor: -1,
    DualA: -1,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 81,
    MSc: 84,
    MSR: -1,
  },
  SEE: {
    BT: -1,
    BS: -1,
    MT: 27,
    DoubleMajor: -1,
    DualA: -1,
    DualB: 105,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 82,
    MSc: -1,
    MSR: 94,
  },
  SSA: {
    BT: -1,
    BS: -1,
    MT: 106,
    DoubleMajor: -1,
    DualA: -1,
    DualB: -1,
    DualC: -1,
    MDes: -1,
    MBA: -1,
    PhD: 114,
    MSc: -1,
    MSR: -1,
  },
};

export const rev = {
  1: "BT-AE",
  2: "BT-BSBE",
  3: "BT-CE",
  4: "BT-CHE",
  5: "BT-CSE",
  6: "BT-EE",
  7: "BT-MSE",
  8: "BT-ME",
  9: "BS-CHM",
  10: "BS-ECO",
  11: "BS-ES",
  12: "BS-MTH",
  95: "BS-SDS",
  13: "BS-PHY",
  28: "DoubleMajor-AE",
  29: "DoubleMajor-BSBE",
  30: "DoubleMajor-CE",
  31: "DoubleMajor-CHE",
  32: "DoubleMajor-CSE",
  33: "DoubleMajor-EE",
  34: "DoubleMajor-MSE",
  35: "DoubleMajor-ME",
  96: "DoubleMajor-CHM",
  36: "DoubleMajor-ECO",
  37: "DoubleMajor-MTH",
  97: "DoubleMajor-SDS",
  98: "DoubleMajor-PHY",
  38: "DualA-AE",
  39: "DualA-BSBE",
  40: "DualA-CE",
  41: "DualA-CHE",
  42: "DualA-CSE",
  43: "DualA-EE",
  44: "DualA-MSE",
  45: "DualA-CHM",
  99: "DualA-ME",
  46: "DualA-ECO",
  47: "DualA-MTH",
  100: "DualA-SDS",
  48: "DualA-PHY",
  49: "DualB-AE",
  50: "DualB-BSBE",
  51: "DualB-CE",
  52: "DualB-CHE",
  53: "<DELETED>DualB-CSE</DELETED>",
  54: "DualB-EE",
  55: "DualB-MSE",
  101: "DualB-ME",
  56: "DualB-ECO",
  102: "DualB-MTH",
  103: "DualB-SDS",
  57: "DualB-PHY",
  58: "DualB-DES",
  59: "<DELETED>DualC-EE</DELETED>",
  104: "DualB-IME",
  105: "DualB-SEE",
  60: "DualC-IME",
  14: "MT-AE",
  15: "MT-BSBE",
  16: "MT-CE",
  17: "MT-CHE",
  18: "MT-CSE",
  19: "MT-EE",
  20: "MT-MSE",
  21: "MT-ME",
  22: "MT-ES",
  23: "MT-IME",
  24: "MT-MSP",
  25: "MT-NET",
  26: "MT-PSE",
  27: "MT-SEE",
  106: "MT-SSA",
  85: "MSR-AE",
  86: "MSR-CE",
  87: "MSR-CHE",
  88: "MSR-CSE",
  89: "MSR-EE",
  90: "MSR-ME",
  91: "MSR-CGS",
  92: "<DELETED>MSR-EEM</DELETED>",
  93: "MSR-PSE",
  94: "MSR-SEE",
  107: "MSc-CHM",
  108: "MSc-ECO",
  109: "MSc-ES",
  110: "MSc-PHY",
  83: "MSc-Stats",
  84: "MSc-Mathematics",
  61: "MDes-DES",
  62: "MBA-IME",
  63: "PhD-AE",
  64: "PhD-BSBE",
  65: "PhD-CE",
  66: "PhD-CHE",
  67: "PhD-CSE",
  68: "PhD-EE",
  69: "PhD-MSE",
  70: "PhD-ME",
  111: "PhD-CHM",
  112: "PhD-ECO",
  71: "PhD-ES",
  72: "<DELETED>PhD-MTH</DELETED>",
  73: "PhD-PHY",
  74: "PhD-CGS",
  75: "PhD-DES",
  76: "PhD-IME",
  113: "PhD-MSP",
  77: "PhD-NET",
  78: "PhD-PSE",
  79: "PhD-Stats",
  80: "PhD-HSS",
  81: "PhD-Mathematics",
  82: "PhD-SEE",
  114: "PhD-SSA",
};

export default { programExpanded, Branches, programCondensed, rev, func };
